"""empty message

Revision ID: 29297f838b0e
Revises: 8dc6f92c4cea
Create Date: 2022-09-26 21:04:40.819676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29297f838b0e'
down_revision = '8dc6f92c4cea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_chat')
    op.drop_index('ix_conversation_text_timestamp', table_name='conversation_text')
    op.drop_table('conversation_text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_text',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('message', sa.VARCHAR(), nullable=True),
    sa.Column('from_user_id', sa.INTEGER(), nullable=True),
    sa.Column('room_id', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room_chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversation_text_timestamp', 'conversation_text', ['timestamp'], unique=False)
    op.create_table('room_chat',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_one', sa.INTEGER(), nullable=True),
    sa.Column('user_two', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_one'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_two'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
