"""add like dislike table

Revision ID: 606f4e6fe76b
Revises: 5d77d277ba42
Create Date: 2022-09-26 14:12:09.323383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '606f4e6fe76b'
down_revision = '5d77d277ba42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dislike_comment',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('like_comment',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('like_comment')
    op.drop_table('dislike_comment')
    # ### end Alembic commands ###
