"""empty message

Revision ID: 8161891aa098
Revises: 250f2a2e4809
Create Date: 2022-09-27 14:44:20.862283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8161891aa098'
down_revision = '250f2a2e4809'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversation_text', type_='foreignkey')
    op.create_foreign_key(None, 'conversation_text', 'room_chat', ['room_id'], ['room_id'])
    op.add_column('room_chat', sa.Column('room_id', sa.Integer(), nullable=False))
    op.drop_column('room_chat', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_chat', sa.Column('id', sa.INTEGER(), nullable=False))
    op.drop_column('room_chat', 'room_id')
    op.drop_constraint(None, 'conversation_text', type_='foreignkey')
    op.create_foreign_key(None, 'conversation_text', 'room_chat', ['room_id'], ['id'])
    # ### end Alembic commands ###
