"""add table chat

Revision ID: 8dc6f92c4cea
Revises: 606f4e6fe76b
Create Date: 2022-09-26 21:01:25.942373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dc6f92c4cea'
down_revision = '606f4e6fe76b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_one', sa.Integer(), nullable=True),
    sa.Column('user_two', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_one'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_two'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation_text',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('from_user_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room_chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_text_timestamp'), 'conversation_text', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_text_timestamp'), table_name='conversation_text')
    op.drop_table('conversation_text')
    op.drop_table('room_chat')
    # ### end Alembic commands ###
