"""empty message

Revision ID: d9a854e46c21
Revises: 504036c22620
Create Date: 2022-09-27 14:14:53.909202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9a854e46c21'
down_revision = '504036c22620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_chat')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_chat',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_one', sa.INTEGER(), nullable=True),
    sa.Column('user_two', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_one'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_two'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
